development:
  adapter: postgresql
  encoding: utf8
  database: postgres_development
  host: localhost
  pool: 5
#  username: sample_postgres
#  password:

test:
  adapter: postgresql
  encoding: utf8
  database: postgres_test
  pool: 5
  host: localhost
#  username: sample_postgres
#  password:

production:
  adapter: postgresql
  encoding: utf8
  database: postgres_production
  pool: 5
  host: localhost
#  username: sample_postgres
#  password:
